[build]
  build = "./"
	publish = "dist"
	command = "npm run build"

[[plugins]]
	# Installs the Lighthouse Build Plugin for all deploy contexts
	package = "@netlify/plugin-lighthouse"
	
	# optional, deploy the lighthouse report to a path under your site
	[plugins.inputs]
		output_path = "./lighthouse.html"
	
	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 0.9
		accessibility = 0.9
		best-practices = 0.9
		seo = 0.9
		pwa = 0.8
		
[[headers]]
	for = "/*"
	
	[headers.values]
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; font-src 'self' 'unsafe-inline' gstatic.com *.gstatic.com; style-src 'self' 'unsafe-inline' googleapis.com *.googleapis.com;"

[[redirects]]
	from = "/hire-me"
	to = "/contact"
	
[[redirects]]	
	from = "/how-to-use-excels-vlookup-to-quickly-update-product-data"
	to = "/blog/how-to-use-excels-vlookup-to-quickly-update-product-data"
	
[[redirects]]	
	from = "/pros-cons-using-wordpress-page-builders/basic-vs-complex-layout"
	to = "/blog/pros-cons-using-wordpress-page-builders/basic-vs-complex-layout"
	
[[redirects]]	
	from = "/progressive-image-loading-with-hubspot"
	to = "/blog/progressive-image-loading-with-hubspot"
	
[[redirects]]	
	from = "/lazy-loading-images-on-hubspot"
	to = "/blog/lazy-loading-images-on-hubspot"
	
[[redirects]]	
	from = "/hubspot-blog-search"
	to = "/blog/hubspot-blog-search"